# Generated by Django 3.1.5 on 2021-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Sevice',
        ),
    ]
