# Generated by Django 3.1.5 on 2021-01-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0003_auto_20210113_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_info',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='login',
            field=models.CharField(max_length=10),
        ),
    ]
