# Generated by Django 3.1.5 on 2021-01-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0004_auto_20210113_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_auto',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service_auto',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service_auto',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_service.service_info'),
        ),
        migrations.AddField(
            model_name='service_info',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad_service.company'),
        ),
        migrations.AddField(
            model_name='service_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='service_info',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='service_info',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='serv'),
        ),
        migrations.AddField(
            model_name='service_info',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='login',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
