# Generated by Django 3.1.5 on 2021-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0005_auto_20210113_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_auto',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service_auto',
            name='engine',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service_auto',
            name='gear_case',
            field=models.CharField(choices=[('автомат', 'автомат'), ('механика', 'механика')], default='механика', max_length=8),
        ),
        migrations.AddField(
            model_name='service_auto',
            name='kilometrage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service_auto',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service_auto',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_info',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='service_info',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
