# Generated by Django 3.1.5 on 2021-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0006_auto_20210114_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_auto',
            name='car_type',
            field=models.CharField(choices=[('минивен', 'минивен'), ('универсал', 'универсал'), ('минивен', 'хэтчбек'), ('купе', 'купе'), ('внедорожник', 'внедорожник'), ('кабриолет', 'кабриолет'), ('пикап', 'пикап')], help_text='тип кузова', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service_auto',
            name='gear',
            field=models.CharField(choices=[('передний', 'передний'), ('задний', 'задний'), ('4х4', '4х4')], default='передний', help_text='Привод', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='service_auto',
            name='engine',
            field=models.CharField(help_text='характеристики двигателя', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='service_auto',
            name='kilometrage',
            field=models.IntegerField(help_text='пробег', null=True),
        ),
    ]
