# Generated by Django 3.1.5 on 2021-01-14 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad_service', '0007_auto_20210114_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_info',
            name='company',
        ),
        migrations.AddField(
            model_name='service_info',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service_auto',
            name='gear_case',
            field=models.CharField(choices=[('автомат', 'автомат'), ('механика', 'механика')], default='механика', help_text='коробка передач', max_length=8),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
