# Generated by Django 3.1.5 on 2021-01-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0008_auto_20210114_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_auto',
            name='kilometrage',
        ),
    ]
