# Generated by Django 3.1.5 on 2021-01-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad_service', '0009_remove_service_auto_kilometrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_visit', models.DateField(verbose_name='Время вашего визита в салон для просмотра автомобиля')),
                ('phone', models.CharField(max_length=12, null=True)),
                ('text', models.TextField(default='Планирую посетить Ваш салон в указанное выше время. Прошу подготовить выбранную машину для тест драйва.', help_text='Дополнительная информация. Пожелания', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
