# Generated by Django 3.1.5 on 2021-01-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_service', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_service.service_auto'),
        ),
    ]
