# Generated by Django 3.1.5 on 2021-01-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210114_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
