# Generated by Django 3.1.5 on 2021-01-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0002_person_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_auto',
            name='owner_info',
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTS', models.CharField(default='оригинал', help_text='ПТС', max_length=30, null=True)),
                ('Vin', models.CharField(help_text='Идентификационный номер транспортного средства', max_length=30, null=True)),
                ('state_number', models.CharField(help_text='гос номер', max_length=20, null=True)),
                ('insurance', models.BooleanField(default=False, verbose_name='tap status')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_person.person_auto')),
            ],
        ),
    ]
