# Generated by Django 3.1.5 on 2021-01-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0005_comment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='person_information',
            name='pasport_info',
            field=models.TextField(blank=True, help_text='паспортные данные', max_length=50, null=True),
        ),
    ]
