# Generated by Django 3.1.5 on 2021-01-15 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad_person', '0007_auto_20210115_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_person.person_auto'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_visit', models.DateField(verbose_name='Время вашего визита в салон для просмотра автомобиля')),
                ('phone', models.CharField(max_length=12, null=True)),
                ('text', models.TextField(default='Планирую посетить Ваш салон в указанное выше время. Прошу подготовить выбранную машину для тест драйва.', help_text='Дополнительная информация. Пожелания', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
