# Generated by Django 3.1.5 on 2021-01-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_person', '0008_auto_20210115_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
